### ISSUE TITLE
卷轴模式下卡片管理界面，右边正文会被左边遮挡住。

### ISSUE THREAD

**Issue by chenshinshi** [StarDustSheep/pink-room#21]
![image](https://user-images.githubusercontent.com/125173405/230753027-291d458c-293e-4fe1-81d0-78d05cc9845c.png)
虽然知道卷轴模式bug多但还是期待个修复|・ﾉω・)

**Comment by chenshinshi** [comment]
这边后来通过在工具栏添加了个卷轴模式开关曲线解决了，用闪卡还有分屏看pdf的时候就关掉，码字就开启。

**Comment by StarDustSheep** [comment]
我研究研究怎么让卷轴模式各种情况都好用

**Comment by chenshinshi** [comment]
> 我研究研究怎么让卷轴模式各种情况都好用

在群里看到啦，期待更新(⁠≧⁠▽⁠≦⁠)

**Comment by StarDustSheep** [comment]
**开启自适应宽度+开启卷轴模式**
闪卡管理界面修改后：
![image](https://user-images.githubusercontent.com/114859111/232397423-1f520c57-16cb-4750-a16d-c41bc5907c4b.png)
搜索界面修改后：
![image](https://user-images.githubusercontent.com/114859111/232395145-e3d21834-dcb3-4559-b1c5-e92ddb0464ee.png)

**Comment by StarDustSheep** [comment]
> > 我研究研究怎么让卷轴模式各种情况都好用
> 
> 在群里看到啦，期待更新(⁠≧⁠▽⁠≦⁠)

我试图使用@container来根据父元素宽度动态地将文字编辑区转换为卷轴页面，但导致了块图标错位，短时间不知道怎么修正，所以只修改一下闪卡界面和搜索页面。
