### ISSUE TITLE
希望可以引入搜索框左右分栏的 样式

### ISSUE THREAD

**Issue by Tlonglan** [StarDustSheep/pink-room#3]
很喜欢你的主题，特别是绿色版本，
**希望可以引入搜索框左右分栏的 样式**，可以作者大大辛苦了！
![image](https://user-images.githubusercontent.com/38731172/202118139-17e205b6-a6db-4892-8988-e81dee98e1f6.png)

![image](https://user-images.githubusercontent.com/38731172/202118610-a481e4c0-39ee-4a38-a703-f069dbe75e3e.png)

**Comment by StarDustSheep** [comment]
我会试着做一下，左右分栏是比较好看点。

**Comment by StarDustSheep** [comment]
思源即将增加这个特性了，用不着我来实现了
