### ISSUE TITLE
视图转换功能

### ISSUE THREAD

**Issue by Jamie-Wan** [StarDustSheep/pink-room#30]
第一次使用，突然发现“猛男粉”确实不错:p但是发现相对其他主体，缺少视图转换功能，希望能够增加，谢谢作者！

**Comment by StarDustSheep** [comment]
俺不会JS，只能在原版基础上做外观修改……

**Comment by Jamie-Wan** [comment]
我不太懂，这个需要JS的知识吗？我看savor和tsundoku主题都有这个功能，可以将列表转换为其他形式。不知道可不可以拿来“借鉴”。不过作者觉得用处不大的话就算了，感谢作者回复！
![视图选择](https://user-images.githubusercontent.com/65280479/236366880-8df5202a-87ca-4f6a-b713-656e323a0429.png)

**Comment by StarDustSheep** [comment]
估计以后会变成插件

**Comment by Jamie-Wan** [comment]
好的，谢谢！

**Comment by StarDustSheep** [comment]
现在集市里有一个“自定义块样式”的插件应该能满足你的需求

**Comment by Jamie-Wan** [comment]
收到，谢谢！
