### ISSUE TITLE
建议被钉住的页面改变一下样式方便区分

### ISSUE THREAD

**Issue by Tlonglan** [StarDustSheep/pink-room#35]
被钉住的页面在操作上有些限制，例如不能移动到其他面板，建议可以加个图钉图标，或者修改一下样式，这样会比较好区分
![image](https://github.com/StarDustSheep/pink-room/assets/38731172/f3437bee-3f1c-43e7-819b-490423a6c420)

**Comment by StarDustSheep** [comment]
确实需要加点特殊的标识，晚些时候我看看做成啥样子好看点

**Comment by StarDustSheep** [comment]
![image](https://github.com/StarDustSheep/pink-room/assets/114859111/bc24d099-b5a9-46e9-a138-21709447f498)
当前先做成这样子
