### ISSUE TITLE
pinkroom主题和（伪）文档面包屑、工具栏plus插件一起用会出现一排空白

### ISSUE THREAD

**Issue by EdwardOwl** [StarDustSheep/pink-room#38]
见下图
![91e6100847802ef607795b243900e98f](https://github.com/StarDustSheep/pink-room/assets/78415230/820ebd4c-4890-40a3-8631-14978ccec03c)

而pinkroom只使用（伪）文档面包屑插件不会有这样的问题
![7fbeaf4fbb0426b596d76782f61aa5ce](https://github.com/StarDustSheep/pink-room/assets/78415230/9a04ca08-c4b6-406a-8ae2-e48a5b84ba17)

pinkroom只使用工具栏plus插件也不会有这样的问题
![ebaacd2c46c0257ebeeee6d6c7736aae](https://github.com/StarDustSheep/pink-room/assets/78415230/daf38c73-efd0-4ef7-be32-1df2b5994822)

**Comment by StarDustSheep** [comment]
“工具栏plus”插件为.protyle-content设置了32px的外部上边距，留出一片区域用来放工具栏元素。但“（伪）面包屑”插件启用的时候，伪面包屑元素和面包屑元素上下排列，而工具栏元素依旧定位在原先的位置，这时候它挡住了面包屑元素，而下面.protyle-content上依旧留有外部上边距，就出现了图中的问题。

**我目前加上了一段兼容代码，这段代码会在伪面包屑元素出现的时候，为工具栏插件的工具栏元素设置单独的定位数值。以防止图中的元素布局错误问题。**
但这种做法对于未来代码变动的兼容性不高。理想情况下应该是工具栏plus插件将toolbar放置到.protyle-breadcrumb和.protyle-content之间，或者说面包屑元素的后面，并使用相对定位，将top和left设为0，然后将.protyle-content的上部外边距取消。使其自然地排列在面包屑元素的下面，这样，就算有人使用别的代码修改了面包屑或者伪面包屑元素的高度，也不会引发视觉上的布局错误。目前“工具栏plus”插件的做法是使用绝对定位，所以出现了不兼容的问题，这种情况不只会出现在我的主题上，别人的主题上很有可能也有此问题。
