### ISSUE TITLE
设置面板的异常白色条纹

### ISSUE THREAD

**Issue by frostime** [StarDustSheep/pink-room#41]
设置面板的分隔符是通过 box-shadow 实现的，由于主题重写了背景颜色，导致出现了异常的白色条纹

![image](https://github.com/StarDustSheep/pink-room/assets/27268127/a889fb91-133d-4251-b0be-47d0401891c2)

**Comment by StarDustSheep** [comment]
好家伙，显示器不好或者没仔细看的话真看不出来。
