### ISSUE TITLE
工作空间名称样式修改

### ISSUE THREAD

**Issue by chenshinshi** [StarDustSheep/pink-room#5]
![image](https://user-images.githubusercontent.com/125173405/218293732-4f646d35-d3ce-42b4-a20c-1a431f06487d.png)
x
现在的样式，左上角工作区域会显示全名，颜色也和其他按钮不协调，看到Savor主题是处理成仅显示首字并用方块包围起来，不知道作者会不会修改呢？

**Comment by StarDustSheep** [comment]
在0.6.1版本中此问题已修复，工作空间名字部分的文字的字色已和主题字色统一。
